#!/bin/bash
#
# Copyright (C) 2018 Klaus Reimer <k@ailis.de>
# See LICENSE.md for licensing information.
#

# Exit on errors
set -e

# Go to base directory of linux build scripts
cd $(dirname $0)

# Build X86 library
./build x86

# Build X86-64 library
./build x86-64

# Build AARCH64 library
./build aarch64 /usr/bin/qemu-aarch64-static

# Build ARM library
./build-arm
