#!/bin/bash
#
# Copyright (C) 2018 Klaus Reimer <k@ailis.de>
# See LICENSE.md for licensing information.
#

# Exit on errors
set -e

# Go to base directory of linux build scripts
cd $(dirname $0)

# Build X86 library
./build x86

# Build X86-64 library
./build x86-64

# Build ARM 64-bit library (ARMv8 and higher)
./build aarch64

# Build ARM 32-bit library (ARMv7 and higher)
./build arm

# Build ARM 32-bit library (ARMv4T and higher)
./build armel
